# Generated by Django 3.0.8 on 2021-02-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_holder', models.CharField(max_length=225)),
                ('Email_ID', models.CharField(max_length=225)),
                ('Current_Balance', models.IntegerField()),
            ],
        ),
    ]
