# Generated by Django 3.0.8 on 2021-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_deatials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender_Name', models.CharField(max_length=225)),
                ('Sender_Current_Balance', models.IntegerField()),
                ('Amount_Transfer', models.IntegerField()),
                ('Reciver_Name', models.CharField(max_length=225)),
            ],
        ),
    ]
