# Generated by Django 3.0.8 on 2021-02-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_transaction_deatials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_deatials',
            old_name='Sender_Current_Balance',
            new_name='Sender_updated_Balance',
        ),
    ]
